{{- if .Values.catalogue.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craftista.fullname" . }}-catalogue-config
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
data:
  MONGODB_HOST: {{ include "craftista.fullname" . }}-mongodb
  MONGODB_PORT: "27017"
  MONGODB_DATABASE: craftista-catalog
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-catalogue
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
spec:
  type: {{ .Values.catalogue.service.type }}
  ports:
    - port: {{ .Values.catalogue.service.port }}
      targetPort: {{ .Values.catalogue.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-catalogue
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalogue
spec:
  replicas: {{ .Values.catalogue.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: catalogue
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: catalogue
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      containers:
        - name: catalogue
          image: "{{ .Values.catalogue.image.repository }}:{{ .Values.catalogue.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.catalogue.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "craftista.fullname" . }}-catalogue-config
          resources:
            {{- toYaml .Values.catalogue.resources | nindent 12 }}
{{- end }}