{{- if and .Values.catalogue.enabled .Values.catalogue.mongodb.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-mongodb
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-mongodb
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ include "craftista.fullname" . }}-mongodb-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "craftista.fullname" . }}-mongodb-pvc
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.catalogue.mongodb.persistence.size }}
  {{- if .Values.catalogue.mongodb.persistence.storageClass }}
  storageClassName: {{ .Values.catalogue.mongodb.persistence.storageClass }}
  {{- end }}
{{- end }}

{{- if and .Values.voting.enabled .Values.voting.postgresql.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "craftista.fullname" . }}-postgresql-secret
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  POSTGRES_USER: {{ .Values.voting.postgresql.auth.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.voting.postgresql.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.voting.postgresql.auth.database | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-postgresql
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgresql
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-postgresql
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ include "craftista.fullname" . }}-postgresql-secret
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          persistentVolumeClaim:
            claimName: {{ include "craftista.fullname" . }}-postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "craftista.fullname" . }}-postgresql-pvc
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.voting.postgresql.persistence.size }}
  {{- if .Values.voting.postgresql.persistence.storageClass }}
  storageClassName: {{ .Values.voting.postgresql.persistence.storageClass }}
  {{- end }}
{{- end }}