{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craftista.fullname" . }}-frontend-config
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  CRAFTISTA_CATALOG_SERVICE_URL: "http://{{ include "craftista.fullname" . }}-catalogue:{{ .Values.catalogue.service.port }}"
  CRAFTISTA_RECOMMEND_SERVICE_URL: "http://{{ include "craftista.fullname" . }}-recommendation:{{ .Values.recommendation.service.port }}"
  CRAFTISTA_VOTING_SERVICE_URL: "http://{{ include "craftista.fullname" . }}-voting:{{ .Values.voting.service.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-frontend
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-frontend
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "craftista.fullname" . }}-frontend-config
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}