{{- if .Values.voting.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "craftista.fullname" . }}-voting-config
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting
data:
  POSTGRES_HOST: {{ include "craftista.fullname" . }}-postgresql
  POSTGRES_PORT: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "craftista.fullname" . }}-voting
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting
spec:
  type: {{ .Values.voting.service.type }}
  ports:
    - port: {{ .Values.voting.service.port }}
      targetPort: {{ .Values.voting.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "craftista.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "craftista.fullname" . }}-voting
  labels:
    {{- include "craftista.labels" . | nindent 4 }}
    app.kubernetes.io/component: voting
spec:
  replicas: {{ .Values.voting.replicaCount }}
  selector:
    matchLabels:
      {{- include "craftista.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: voting
  template:
    metadata:
      labels:
        {{- include "craftista.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: voting
    spec:
      {{- if .Values.rbac.create }}
      serviceAccountName: {{ .Values.rbac.serviceAccountName }}
      {{- end }}
      containers:
        - name: voting
          image: "{{ .Values.voting.image.repository }}:{{ .Values.voting.image.tag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.voting.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "craftista.fullname" . }}-voting-config
            - secretRef:
                name: {{ include "craftista.fullname" . }}-postgresql-secret
          resources:
            {{- toYaml .Values.voting.resources | nindent 12 }}
{{- end }}