apiVersion: v1
kind: ConfigMap
metadata:
  name: craftista-frontend-config
  labels:
    app: craftista-frontend
    service: craftista-frontend
    config: craftista-frontend
data:
  CRAFTISTA_CATALOG_SERVICE_URL: "http://craftista-catalog-service:5000"
  CRAFTISTA_RECOMMEND_SERVICE_URL: "http://craftista-recommend-service:8000"
  CRAFTISTA_VOTING_SERVICE_URL: "http://craftista-voting-service:8060"
---
apiVersion: v1
kind: Service
metadata:
  name: craftista-frontend-service
  labels:
    app: craftista-frontend
    service: craftista-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: craftista-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: craftista-frontend
  labels:
    app: craftista-frontend
    service: craftista-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: craftista-frontend
  template:
    metadata:
      labels:
        app: craftista-frontend
        service: craftista-frontend
    spec:
      containers:
        - name: craftista-frontend
          image: hema995/craftista-frontend:6
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi  
          imagePullPolicy: Always   
---
 