apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpilot-catalogue
  labels: 
     app.kubernetes.io/name: cloudpilot-catalogue
     app.kubernetes.io/component: catalogue
     app.kubernetes.io/part-of: cloudpilot
     app.kubernetes.io/instance: cloudpilot
     app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudpilot-catalogue
      app.kubernetes.io/component: catalogue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudpilot-catalogue
        app.kubernetes.io/component: catalogue
        app.kubernetes.io/part-of: cloudpilot
        app.kubernetes.io/instance: cloudpilot
    spec:
      serviceAccountName: cloudpilot-catalogue
      containers:
        - name: catalogue
          image: catalogue-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: tcp-service
          env:
            - name: PORT
              value: "5000"
            - name: POSTGRES_USER
              value: "devops"
            - name: POSTGRES_PASSWORD
              value: "devops"
            - name: POSTGRES_DB
              value: "catalogue"
            - name: POSTGRES_HOST
              value: "catalogue-db"
          resources:
            limits:
              memory: 300Mi
          securityContext:
            runAsNonRoot: true


