apiVersion: v1
kind: Service
metadata:
  name: cloudpilot-catalogue
  labels:
    app.kubernetes.io/name: cloudpilot-catalogue
    app.kubernetes.io/component: catalogue
    app.kubernetes.io/part-of: cloudpilot
    app.kubernetes.io/instance: cloudpilot
    app.kubernetes.io/version: "1.0.0"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloudpilot-catalogue
    app.kubernetes.io/component: catalogue
  ports:
    - port: 5000
      name: tcp-service
      targetPort: 5000
      


