apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base
  - stage-namespace.yaml
  - stage-serviceaccount.yaml
  - stage-role.yaml
  - stage-rolebinding.yaml