apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: stage-rolebinding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: stage-serviceaccount
  namespace: staging
roleRef:
  kind: Role
  name: stage-role
  apiGroup: rbac.authorization.k8s.io