apiVersion: v1
kind: Service
metadata:
  name: cloudpilot-voting
  labels:
    app.kubernetes.io/name: ccloudpilot-voting
    app.kubernetes.io/component: voting
    app.kubernetes.io/part-of: cloudpilot
    app.kubernetes.io/instance: cloudpilot
    app.kubernetes.io/version: "1.0.0"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloudpilot-voting
    app.kubernetes.io/component: voting
  ports:
    - port: 8080
      name: voting-svc
      targetPort: 8080
      


