apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: craftista-dev-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NORTEX0030/CloudPilot.git
    targetRevision: main
    path: helm-charts/craftista
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true