apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudpilot-frontend
  labels: 
     app.kubernetes.io/name: cloudpilot-frontend
     app.kubernetes.io/component: frontend
     app.kubernetes.io/part-of: cloudpilot
     app.kubernetes.io/instance: cloudpilot
     app.kubernetes.io/version: "1.0.0"
spec:
  replicas: 1 
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudpilot-frontend
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudpilot-frontend
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: cloudpilot
        app.kubernetes.io/instance: cloudpilot
    spec:
      serviceAccountName: cloudpilot-frontend
      containers:
        - name: frontend
          image: frontend-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: tcp-service
          env:
            - name: PORT
              value: "3000"
            - name: CATALOGUE_SERVICE_HOST
              value: "catalogue"
            - name: CATALOGUE_SERVICE_PORT
              value: "5000"
          resources:
            limits:
              memory: 250Mi
          securityContext:
            runAsNonRoot: true


