apiVersion: v1
kind: Service
metadata:
  name: cloudpilot-frontend
  labels:
    app.kubernetes.io/name: cloudpilot-frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: cloudpilot
    app.kubernetes.io/instance: cloudpilot
    app.kubernetes.io/version: "1.0.0"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloudpilot-frontend
    app.kubernetes.io/component: frontend
  ports:
    - port: 3000
      name: tcp-service
      targetPort: 3000
      


