apiVersion: v1
kind: Service
metadata:
  name: cloudpilot-recommendation
  labels:
    app.kubernetes.io/name: cloudpilot-recommendation
    app.kubernetes.io/component: catalogue
    app.kubernetes.io/part-of: cloudpilot
    app.kubernetes.io/instance: cloudpilot
    app.kubernetes.io/version: "1.0.0"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: cloudpilot-recommendation
    app.kubernetes.io/component: recommendation
  ports:
    - port: 8080
      name: recom-service
      targetPort: 8080
      


